#!/usr/bin/perl

use strict;
use warnings;

my @freq;
my $nchr;

open my $in, "-|", "man openssl" or die $!;
open my $out, ">", "freq.h" or die $!;

$nchr = 0;

while (<$in>) {
	foreach (split //) {
		$nchr++;
		if (/[A-Za-z]/) {
			$freq[1 + ord(lc $_) - ord('a')]++;
		} elsif ($_ eq ' ') {
			$freq[0]++;
		}
	}
}

print $out "/* Generated by freq.pl */\n\n";

print $out "float freq[] = {\n";
for my $i (0 .. 26) {
	$freq[$i] += 0;
	$freq[$i] /= $nchr;

	printf $out "\t%f,\n", $freq[$i];
}
print $out "};"
