#!/usr/bin/perl

use strict;
use warnings;

my @tab;
my $nchr;

open my $fh, "-|", "man openssl" or die $!;
$nchr = 0;

while (<$fh>) {
	foreach (split //) {
		$nchr++;
		if (/[A-Za-z]/) {
			$tab[1 + ord(lc $_) - ord('a')]++;
		} elsif ($_ eq ' ') {
			$tab[0]++;
		}
	}
}

print "/* Generated by tab.pl */\n\n";

print "float tab[] = {\n";
for my $i (0 .. 26) {
	$tab[$i] += 0;
	$tab[$i] /= $nchr;

	printf "\t%f,\n", $tab[$i];
}
print "};"
