#!/usr/bin/perl

use strict;
use warnings;

my @tab;
my $nchr;

open my $in, "-|", "man openssl" or die $!;
open my $out, ">", "tab.h" or die $!;

$nchr = 0;

while (<$in>) {
	foreach (split //) {
		$nchr++;
		if (/[A-Za-z]/) {
			$tab[1 + ord(lc $_) - ord('a')]++;
		} elsif ($_ eq ' ') {
			$tab[0]++;
		}
	}
}

print $out "/* Generated by tab.pl */\n\n";

print $out "float tab[] = {\n";
for my $i (0 .. 26) {
	$tab[$i] += 0;
	$tab[$i] /= $nchr;

	printf $out "\t%f,\n", $tab[$i];
}
print $out "};"
